## [NumPy](http://www.numpy.org/)

NumPy is a low level, mathematical package for numerical computations.

- Its fundamental data structure is the [n-dimensional array](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html).
- It was written in C. The usual array operations are implemented efficiently.
- Among others, it contains submodules for linear algebra and random number generation.
- Several higher level packages (e.g. scipy, matplotlib, pandas, scikit-learn) are based on it.
- NumPy is an external package, it is not part of the standard library.

In [2]:
# Importing NumPy under the name np.
import numpy as np

In [2]:
# Querying the version number.
np.__version__

'1.23.5'

#### Creating arrays

In [3]:
# Create a 1-dimensional array of integers.
a = np.array([2,3,4])

In [4]:
a

array([2, 3, 4])

In [5]:
# Type of the array object.
type(a)

numpy.ndarray

In [6]:
# Number of dimensions.
a.ndim

1

In [5]:
b = np.array([(2,2,2,2,2),(3,3,3,3,3)])

In [6]:
b.size

10

In [4]:
a.size

3

In [7]:
# Size of dimensions.
a.shape

(3,)

In [8]:
# The data type of the array elements.
# Arrays in are homogenous in NumPy (except the object array).
a.dtype

dtype('int64')

In [9]:
# Create a 2-dimensional array of floats.
b = np.array([[2.0,3,4], [5,6,7]])

In [10]:
b

array([[2., 3., 4.],
       [5., 6., 7.]])

In [11]:
# Number and size of dimensions, data type.
b.ndim

2

In [12]:
# Specifying the data type of elements, example 1.
b.shape

(2, 3)

In [13]:
# Specifying the data type of elements, example 2.
b.dtype

dtype('float64')

In [15]:
# Create an array of int8
np.array([0]*10000, dtype='int8')

array([0, 0, 0, ..., 0, 0, 0], dtype=int8)

In [16]:
# Create an array of float32
np.array([4,5,6], dtype='float32')

array([4., 5., 6.], dtype=float32)

In [17]:
# Loading an array from text file.
np.loadtxt('matrix.txt', dtype='int32')

array([[0, 1, 1, 0, 1, 0, 1, 1, 0, 1],
       [0, 0, 1, 0, 1, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 0, 1, 1, 0, 0],
       [0, 1, 0, 0, 1, 0, 1, 1, 0, 0],
       [1, 0, 1, 1, 0, 0, 1, 0, 1, 1],
       [1, 0, 1, 0, 0, 1, 1, 0, 1, 0],
       [1, 1, 1, 0, 1, 1, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [1, 1, 0, 1, 0, 1, 1, 1, 0, 0],
       [1, 0, 1, 0, 1, 0, 0, 1, 0, 1]], dtype=int32)

In [18]:
# Create an array of zeros, example 1.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
# Create an array of zeros, example 2.
np.zeros((3,4), dtype='uint16')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint16)

In [20]:
# Create an array of ones, example 1.
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [21]:
# Create an array of ones, example 2.
np.ones((2,2,2), dtype='int8')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int8)

In [22]:
# Create an identity matrix.
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [88]:
# Create a range by specifying the step size.
np.arange(-5,2,0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5])

In [90]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
# Create a range by specifying the number of elements.
np.linspace(-5,2,20)

array([-5.        , -4.63157895, -4.26315789, -3.89473684, -3.52631579,
       -3.15789474, -2.78947368, -2.42105263, -2.05263158, -1.68421053,
       -1.31578947, -0.94736842, -0.57894737, -0.21052632,  0.15789474,
        0.52631579,  0.89473684,  1.26315789,  1.63157895,  2.        ])

In [93]:
# Concatenating vectors.
a = np.array([2, 3, 4])
b = np.array([10, 20])
np.concatenate([a,b])

array([ 2,  3,  4, 10, 20])

In [94]:
# Stacking matrices horizontally.
a = np.array([
    [2, 3, 4],
    [5, 6, 7]
])
np.hstack([a,a])

array([[2, 3, 4, 2, 3, 4],
       [5, 6, 7, 5, 6, 7]])

In [95]:
# Stacking matrices vertically.
np.vstack([a,a])

array([[2, 3, 4],
       [5, 6, 7],
       [2, 3, 4],
       [5, 6, 7]])

#### Elements ans subarrays

In [3]:
# Let's create an example matrix!
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [4]:
# Select an element (indexing starts from 0)
a[0,1]

2

In [5]:
# .... equivalent to:
a[(0,1)]

2

In [6]:
# Selecting a full row.
a[1,:]

array([4, 5, 6])

In [7]:
# We could also do it this way.
a[1]

array([4, 5, 6])

In [8]:
# The selected row is a 1-dimensional array.
a[1].shape

(3,)

In [9]:
# Selecting a column.
a[:,2]

array([3, 6])

In [10]:
# Selecting a subarray.
a[:, :-1]

array([[1, 2],
       [4, 5]])

In [11]:
a[:, [0,2]]

array([[1, 3],
       [4, 6]])

In [13]:
# Selecting elements based on a logical condition.
a[a>2]

array([3, 4, 5, 6])

In [14]:
a>2

array([[False, False,  True],
       [ True,  True,  True]])

In [15]:
# The elements of the array can be modified.
a[0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [16]:
# Modifying a column.
a[:, 1] = [30, 40]
a

array([[100,  30,   3],
       [  4,  40,   6]])

#### Array operations

In [17]:
# Let's create 2 example arrays!
a = np.array([2, 3, 4])
b = np.array([1, 2, 3])

In [18]:
# Elementwise addition.
a+b

array([3, 5, 7])

In [19]:
# Elementwise subtraction.
a-b

array([1, 1, 1])

In [20]:
# Elementwise multiplication.
a*b

array([ 2,  6, 12])

In [21]:
# Elementwise division.
a/b

array([2.        , 1.5       , 1.33333333])

In [22]:
# Elementwise integer division.
a//b

array([2, 1, 1])

In [23]:
# Elementwise exponentiation.
a**b

array([ 2,  9, 64])

In [25]:
# The operation is not necessarily doable.
a = np.array([1, 2])
b = np.array([1, 2, 3])
a+b

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [26]:
# Elementwise functions (exp, log, sin, cos, ...).
np.exp(a)

array([2.71828183, 7.3890561 ])

In [27]:
np.sin(b)

array([0.84147098, 0.90929743, 0.14112001])

In [38]:
# Statistical operations (min, max, sum, mean, std).
c = np.array([
    [2, 3, 4],
    [5, 6, 10]
])
c

array([[ 2,  3,  4],
       [ 5,  6, 10]])

In [33]:
c.min()

2

In [34]:
c.std()

2.581988897471611

In [35]:
c.mean()

5.0

In [37]:
# Columnwise statistics.
# We aggregate along the 0-th dimension i.e. rows, therefore this dimension will disappear.
c.sum(axis=0)

array([ 7,  9, 14])

In [39]:
# Rowwise statistics.
# We aggregate along the 1-st dimension i.e. columns, therefore this dimension will disappear.
c.max(axis=1)

array([ 4, 10])

In [41]:
# Exercise: Create a 3×3 NumPy array of logical True values.
np.ones((3,3), dtype='bool')

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [44]:
np.array([[[True]*3]*3])

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [45]:
# Exercise: Print the values greater than the average value in the following NumPy array!
a = np.array([
    [2, 4, 11],
    [5, 6, 7]
])
print(a[a > a.mean()])

[11  6  7]


In [50]:
# Type conversion.
a = np.array([2, 3, 4])
b = a.astype('float32')
b

array([2., 3., 4.], dtype=float32)

In [54]:
# Matrix transpose.
a = np.array([
    [2, 3, 4],
    [5, 6, 7]
])
a.T

array([[2, 5],
       [3, 6],
       [4, 7]])

In [53]:
# Transposition does not copy. It only creates a new view on the original data.
b = a.T
b[0,1] = 100
a

array([[  2,   3,   4],
       [100,   6,   7]])

In [56]:
# ...if we want to create a new array:
a = np.array([
    [2, 3, 4],
    [5, 6, 7]
])
b = a.T.copy()
b[0,1] = 100
print (a)
print (b)

[[2 3 4]
 [5 6 7]]
[[  2 100]
 [  3   6]
 [  4   7]]


In [60]:
# Create an example array of size 12!
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [63]:
# reshape to 3 x 4
a.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
a.reshape((3,-1)) # automaticly compute the second value if possible

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
a.reshape((5,-1))

ValueError: cannot reshape array of size 12 into shape (5,newaxis)

In [68]:
a.reshape((-1,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [69]:
a.reshape((2,2,-1))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [70]:
# Assignment does not copy in NumPy.
a = np.array([1,2,3])
b = a
b[0] = 100
a

array([100,   2,   3])

In [71]:
# We can copy using the copy method.
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
a

array([1, 2, 3])

In [72]:
# Scalar product of two vectors.
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
a @ b

12

In [73]:
# Matrix multiplication.
a = np.array([
    [2, 3, 4],
    [5, 6, 7]
])
a.T @ a

array([[29, 36, 43],
       [36, 45, 54],
       [43, 54, 65]])

In [74]:
a @ a.T

array([[ 29,  56],
       [ 56, 110]])

#### [Broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
- Broadcasting is a mechanism to handle operands with different shape.
- Example: 
```
A (4d array):      8 x 1 x 6 x 5
B (3d array):          7 x 1 x 5
Result (4d array): 8 x 7 x 6 x 5```

In [80]:
# Multiplying a vector by a scalar.
a = np.array([2, 3, 4])
b = 10
# 3
# -
# 3
a*b

array([20, 30, 40])

In [81]:
a+b

array([12, 13, 14])

In [78]:
# Example for non-broadcastable arrays.
a = np.array([2, 3, 4])
b = np.array([5, 6])
a*b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [85]:
# Multiplying a matrix by a vector.
a = np.array([
    [2, 3, 4],
    [5, 6, 7]
])
b = np.array([1, 2, 3])
# 2 x 3
# - x 3
# 2 x 3
a*b

array([[ 2,  6, 12],
       [ 5, 12, 21]])

In [86]:
a-b

array([[1, 1, 1],
       [4, 4, 4]])

In [84]:
# Rowwise multiplication.
a = np.array([
    [2, 3, 4],
    [5, 6, 7]
])
b = np.array([1, 2])
(a.T*b).T

array([[ 2,  3,  4],
       [10, 12, 14]])

In [3]:
##Exersises

In [6]:
# write a Numpy program to replace the negative values in a Numpy array with 0!
a = np.array([2, 0, -3, 10, -5, 11])
a[a<0] = 0
a

array([ 2,  0,  0, 10,  0, 11])

In [31]:
# write a Numpy program to create an n-by-n array with 1 on the border and 0 inside!
n = 10
a = np.zeros((n,n))
a[[(0), (-1)]] = 1
a[:,0] = 1
a[:,-1] = 1
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [30]:
n = 10
a = np.ones((n,n))
a[1:-1, 1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [42]:
# write a Numpy program to add a border (filled with zeros) around an existing 2D array!
a = np.arange(12).reshape((3,4))
b = np.zeros((a.shape[0]+2, a.shape[1]+2))
b[1:-1,1:-1] = a
b

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  2.,  3.,  0.],
       [ 0.,  4.,  5.,  6.,  7.,  0.],
       [ 0.,  8.,  9., 10., 11.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [55]:
# write a Numpy program to create an nxn matrix and fill it with a checkerboarder patern!
# 0 1 0 1
# 1 0 1 0 
# 0 1 0 1
# 1 0 1 0
# .
# .
n=8
a = np.ones ((n,n))
a[::2,::2] = 0
a[1::2,1::2]=0
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [72]:
# write a Numpy program to find common values between two vectors!
a = np.array([2,3,4,5])
b = np.array([1,3,4,10,11])
c = np.array([a[i] for i in range(0,len(a)) if a[i] in b])
c

array([3, 4])

In [74]:
# 2nd solution
a[np.in1d(a,b)]

array([3, 4])

In [91]:
# write a Numpy program to sum all the multiples of 3 or 5 bellow 100
np.array([i for i in range(3,100) if i%3==0 or i%5==0]).sum()

2318

In [90]:
a = np.arange(1,100)
a[(a % 3 == 0) | ( a % 5 == 0)].sum()

2318